### PR TITLE
Add travis support

### PR DESCRIPTION
**Pull request by rnestler**
Since we have multiple contributors now it would make sense to use CI.

### CODE REVIEW

**Comment by rnestler** [comment]
@ubruhin care to review? Just post a :+1: or similar if you think it looks OK

**Comment by ubruhin** [comment]
are you sure that this project compiles with the latest rust stable? on my computer this did not work...

**Comment by rnestler** [comment]
Travis says it works so I guess it does :wink:

**Comment by ubruhin** [comment]
:+1:

**Pull request merged**
