### PR TITLE
Add kickass searchprovider

### PR DESCRIPTION
**Pull request by ubruhin**
(not yet finished)

### CODE REVIEW

**Comment by rnestler** [comment]
Nice! :smile:

**Comment by rnestler** [comment]
If we add more providers that need decompression, we should refactor it to make it reusable.

**Comment by ubruhin** [comment]
You're right, that would make sense. But this branch isn't finished anyway.

I'm wondering how to create a vector of SearchProvider, so that we can add a PirateBaySearch and a KickassSearch to that vector (in main.rs)?

**Comment by rnestler** [comment]
Since they have different types we need to store them either in an [`enum`](https://doc.rust-lang.org/book/enums.html) or in a dynamically dispatched [trait object](https://doc.rust-lang.org/book/trait-objects.html).

**Comment by rnestler** [comment]
To create a vector of trait objects you would use something like the following:
```Rust
let providers: Vec<Box<SearchProvider>> = vec![
  Box::new(PirateBaySearch::new()),
  Box::new(KickassSearch::new()),
];
```

**Pull request merged**
